image/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
]

image_tank/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'', include('image.urls', namespace='image')),
]

member/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

image/models.py
from django.conf import settings
from django.db import models


class Image(models.Model):
    likes = models.PositiveIntegerField(default=0)
    photo = models.ImageField(upload_to='')
    uploaded_date = models.DateTimeField(auto_now_add=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.photo.name

member/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models


class MemberManager(BaseUserManager):
    def create_user(self, member_id, name, password, email=None):
        member_id = self.model.normalize_username(member_id)
        user = self.model(member_id=member_id,
                          name=name,
                          email=email,)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, member_id, name, password, email=None):
        user = self.create_user(member_id, name, password, email)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class Member(AbstractBaseUser, PermissionsMixin):
    member_id = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=40, blank=True, null=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'member_id'
    REQUIRED_FIELDS = ['name',]

    objects = MemberManager()

    def __str__(self):
        return self.member_id

    def get_short_name(self):
        return self.__str__()

    def get_full_name(self):
        return self.member_id + ": " + self.name

member/forms.py
from django import forms
from member.models import Member


class MemberLoginForm(forms.Form):
    member_id = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class MemberSignupForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Member
        fields = ['member_id', 'password1', 'password2', 'name']

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 != password2:
            raise forms.ValidationError("비밀번호가 다릅니다.")

        return password1

image/views.py
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.shortcuts import redirect, render


def index(request):
    return render(request, 'image/index.html')

member/views.py
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.shortcuts import redirect, render
from member.forms import MemberLoginForm, MemberSignupForm
from .models import Member


def login(request):
    if request.method == 'POST':
        form = MemberLoginForm(request.POST, label_suffix='')
        if form.is_valid():
            member_id = form.cleaned_data.get('member_id')
            password = form.cleaned_data.get('password')
            user = authenticate(member_id=member_id, password=password)

            if user is not None and user.is_active:
                auth_login(request, user)
                return redirect('image:index')
    else:
        form = MemberLoginForm(label_suffix='')

    return render(request, 'member/login.html', {'form': form})


def logout(request):
    auth_logout(request)
    return render(request, 'image/index.html')


def signup(request):
    if request.method == 'POST':
        form = MemberSignupForm(request.POST, label_suffix='')
        if form.is_valid():
            data = form.cleaned_data
            member_id = data.get('member_id')
            password1 = data.get('password1')
            password2 = data.get('password2')
            name = data.get('name')

            user = Member.objects.create_user(member_id=member_id,
                                              password=password1,
                                              name=name,)
            auth_login(request, user)
            return render(request, 'image/index.html')
    else:
        form = MemberSignupForm(label_suffix='')
    return render(request, 'member/signup.html', {'form': form})

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="refresh" content='30'>
  <meta http-equiv="author" content="sunghwan">
  <meta http-equiv="description" content="Image tank site">
  <meta http-equiv="keywords" content="image,django,python">
  <link rel="stylesheet" href="{% static 'style.css' %}" media="all">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.css">
  <title>image tank!!</title>
</head>
<body>
	<nav id="menu">
		<ul>
      {% if request.user.is_authenticated %}
      <a href="{% url 'member:logout' %}"><li>로그아웃</li></a>
      {% else %}
      <a href="{% url 'member:signup' %}"><li>회원가입</li></a>
      <a href="{% url 'member:login' %}"><li>로그인</li></a>
      {% endif %}
      <a href=""><li>사진 업로드</li></a>
      <a href=""><li>사진 목록 확인</li></a>
		</ul>
	</nav>

	<section id="bg">
		{% block 'content' %}

		{% endblock %}
	</section>
	

</body>
</html>

templates/image/index.html
{% extends 'base.html' %}
{% block 'content' %}


{% endblock %} 

templates/member/login.html
{% extends 'base.html' %}


{% block 'content' %}


<form action="{% url 'member:login' %}" method="POST">
  {% csrf_token %}
  {{ form.as_table }}
  <button type="submit">제출</button>
</form>


{% endblock %}

templates/member/signup.html
{% extends 'base.html' %}

{% block 'content' %}

  <form action="" method="POST">
    {% csrf_token %} 
    {{ form.as_p }}
    <button type="submit">회원가입</button>
  </form>
{% endblock %}